FROM node:22-alpine
WORKDIR /app

RUN corepack enable pnpm

COPY .npmrc package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY apps/web/package.json ./apps/web/

#RUN npm install -g pnpm@11
RUN pnpm install --frozen-lockfile

EXPOSE 3000
#CMD ["npm", "run", "dev", "-w", "apps/web"]
CMD ["pnpm", "--filter", "web", "dev"]