sonar.projectKey=saga-ucr
sonar.projectName=SAGA UCR

sonar.sources=apps/api/src,apps/web/src
sonar.tests=apps/api/src
sonar.test.inclusions=apps/api/src/**/__tests__/**/*.ts,apps/api/src/**/__tests__/**/*.tsx

sonar.sourceEncoding=UTF-8
