FROM node:22-alpine
WORKDIR /app

RUN corepack enable pnpm

COPY .npmrc package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY apps/api/package.json ./apps/api/

#RUN npm install -g pnpm@11
RUN pnpm install --frozen-lockfile

EXPOSE 3001
#CMD ["npm", "run", "dev", "-w", "apps/api"]
CMD ["pnpm", "--filter", "api", "dev"]