- name: Sync repos
  run: |
    git clone --branch develop https://JORGE.QUIROSANDERSON:${{ secrets.GITUCR_TOKEN }}@git.ucr.ac.cr/project/saga_ucr.git repo
    cd repo

    git remote add github https://${{ secrets.GH_TOKEN }}@github.com/Joax48/Saga.git

    # Traer main de GitHub
    git fetch github main

    # Crear rama main basada en develop
    git checkout -B main

    # Hacer merge con lo que ya existe en GitHub
    git merge github/main --allow-unrelated-histories -X theirs

    # Push normal (ya no falla)
    git push github main
