name: Sync develop (GitUCR) to main (GitHub)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Clone GitUCR repo (develop)
        run: |
          git clone --branch develop https://JORGE.QUIROSANDERSON:${{ secrets.GITUCR_TOKEN }}@git.ucr.ac.cr/project/saga_ucr.git repo
          cd repo

          git remote add github https://${{ secrets.GH_TOKEN }}@github.com/Joax48/Saga.git
          
          git fetch github main || true
          git checkout -B main
          git merge origin/develop --allow-unrelated-histories -X theirs
          
          git push github main
